"""initial schema

Revision ID: 39038a4a6068
Revises: 
Create Date: 2026-05-09 00:08:34.145398
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '39038a4a6068'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=20), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['refresh_tokens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_revoked_at'), 'refresh_tokens', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('external_links', sa.JSON(), nullable=True),
    sa.Column('readme_overview', sa.Text(), nullable=True),
    sa.Column('contribution_guideline', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_author_id'), 'repositories', ['author_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('raw_content', sa.Text(length=4294967295), nullable=True),
    sa.Column('structured_content', sa.JSON(), nullable=True),
    sa.Column('contribution_types', sa.JSON(), nullable=True),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='visibility'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACCEPTED', 'CHANGES_REQUESTED', 'REJECTED', 'MERGED', name='pullrequeststatus'), nullable=False),
    sa.Column('author_grade_override', sa.Enum('MAJOR', 'NORMAL', 'MINOR', name='contributiongrade'), nullable=True),
    sa.Column('author_grade_override_reason', sa.Text(), nullable=True),
    sa.Column('author_review_comment', sa.Text(), nullable=True),
    sa.Column('changes_requested_reason', sa.Text(), nullable=True),
    sa.Column('contributor_comment', sa.Text(), nullable=True),
    sa.Column('first_drafted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_requests_author_id'), 'pull_requests', ['author_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_repository_id'), 'pull_requests', ['repository_id'], unique=False)
    op.create_index(op.f('ix_pull_requests_status'), 'pull_requests', ['status'], unique=False)
    op.create_index(op.f('ix_pull_requests_submitted_at'), 'pull_requests', ['submitted_at'], unique=False)
    op.create_table('recruiting_areas',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiting_areas_repository_id'), 'recruiting_areas', ['repository_id'], unique=False)
    op.create_table('repo_characters',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_characters_repository_id'), 'repo_characters', ['repository_id'], unique=False)
    op.create_table('repo_forbidden',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_forbidden_repository_id'), 'repo_forbidden', ['repository_id'], unique=False)
    op.create_table('repo_regions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_regions_repository_id'), 'repo_regions', ['repository_id'], unique=False)
    op.create_table('repo_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_rules_repository_id'), 'repo_rules', ['repository_id'], unique=False)
    op.create_table('repository_tags',
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('repository_id', 'tag_id')
    )
    op.create_index(op.f('ix_repository_tags_tag_id'), 'repository_tags', ['tag_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
    sa.Column('run_seq', sa.Integer(), nullable=False),
    sa.Column('generated_title', sa.String(length=300), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('structured_content', sa.JSON(), nullable=True),
    sa.Column('contribution_types', sa.JSON(), nullable=True),
    sa.Column('score_scope', sa.Integer(), nullable=False),
    sa.Column('score_permanence', sa.Integer(), nullable=False),
    sa.Column('score_cascade', sa.Integer(), nullable=False),
    sa.Column('score_alignment', sa.Integer(), nullable=False),
    sa.Column('score_specificity', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('ai_grade', sa.Enum('MAJOR', 'NORMAL', 'MINOR', name='contributiongrade'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('missing_info', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id', 'run_seq', name='uq_ai_analyses_pr_run_seq')
    )
    op.create_index(op.f('ix_ai_analyses_pull_request_id'), 'ai_analyses', ['pull_request_id'], unique=False)
    op.create_table('merges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=False),
    sa.Column('contributor_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('final_grade', sa.Enum('MAJOR', 'NORMAL', 'MINOR', name='contributiongrade'), nullable=False),
    sa.Column('author_comment', sa.Text(), nullable=True),
    sa.Column('credit_text', sa.String(length=500), nullable=False),
    sa.Column('readme_apply_note', sa.Text(), nullable=True),
    sa.Column('citation_url', sa.String(length=500), nullable=False),
    sa.Column('merged_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contributor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pull_request_id')
    )
    op.create_index(op.f('ix_merges_contributor_id'), 'merges', ['contributor_id'], unique=False)
    op.create_index(op.f('ix_merges_repository_id'), 'merges', ['repository_id'], unique=False)
    op.create_table('reject_reasons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.Enum('CONFLICT', 'TOO_VAGUE', 'OUT_OF_SCOPE', 'MISALIGNED', 'DUPLICATE', 'INAPPROPRIATE', 'OTHER', name='rejectcategory'), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('superseded_by_id', sa.BigInteger(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['reject_reasons.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reject_reasons_pull_request_id'), 'reject_reasons', ['pull_request_id'], unique=False)
    op.create_table('view_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pull_request_id', sa.BigInteger(), nullable=False),
    sa.Column('viewer_id', sa.BigInteger(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('day_bucket_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_view_logs_id')
    )
    op.create_index(op.f('ix_view_logs_pull_request_id'), 'view_logs', ['pull_request_id'], unique=False)
    op.create_index(op.f('ix_view_logs_viewer_id'), 'view_logs', ['viewer_id'], unique=False)
    op.create_table('conflict_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_analysis_id', sa.BigInteger(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='conflictrisklevel'), nullable=False),
    sa.Column('check_target', sa.String(length=50), nullable=False),
    sa.Column('target_ref_id', sa.BigInteger(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('missing_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_analysis_id'], ['ai_analyses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conflict_checks_ai_analysis_id'), 'conflict_checks', ['ai_analysis_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conflict_checks_ai_analysis_id'), table_name='conflict_checks')
    op.drop_table('conflict_checks')
    op.drop_index(op.f('ix_view_logs_viewer_id'), table_name='view_logs')
    op.drop_index(op.f('ix_view_logs_pull_request_id'), table_name='view_logs')
    op.drop_table('view_logs')
    op.drop_index(op.f('ix_reject_reasons_pull_request_id'), table_name='reject_reasons')
    op.drop_table('reject_reasons')
    op.drop_index(op.f('ix_merges_repository_id'), table_name='merges')
    op.drop_index(op.f('ix_merges_contributor_id'), table_name='merges')
    op.drop_table('merges')
    op.drop_index(op.f('ix_ai_analyses_pull_request_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_repository_tags_tag_id'), table_name='repository_tags')
    op.drop_table('repository_tags')
    op.drop_index(op.f('ix_repo_rules_repository_id'), table_name='repo_rules')
    op.drop_table('repo_rules')
    op.drop_index(op.f('ix_repo_regions_repository_id'), table_name='repo_regions')
    op.drop_table('repo_regions')
    op.drop_index(op.f('ix_repo_forbidden_repository_id'), table_name='repo_forbidden')
    op.drop_table('repo_forbidden')
    op.drop_index(op.f('ix_repo_characters_repository_id'), table_name='repo_characters')
    op.drop_table('repo_characters')
    op.drop_index(op.f('ix_recruiting_areas_repository_id'), table_name='recruiting_areas')
    op.drop_table('recruiting_areas')
    op.drop_index(op.f('ix_pull_requests_submitted_at'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_status'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_repository_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_author_id'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_repositories_author_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
